### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by mackoj** [luckymarmot/Paw-SwiftNSURLSessionCodeGenerator#6]
Have you considered do a swift 3 support of this plugin ?

**Comment by mittsh** [comment]
Absolutely it's coming. We've just updated the [Alamofire code generator](https://www.github.com/luckymarmot/Paw-SwiftAlamofireCodeGenerator) to be Swift 3 / Alamofire 4. So this one is coming soon.
